# Announcer module configuration
# Rotates messages by timer, supports PlaceholderAPI
# Цветовая палитра: Grief Orange (#FF4D00), Solar Flare (#FAA300), Scorched Earth (#1A120B)

# Interval between messages (seconds)
interval-seconds: 300

# Messages (MiniMessage), rotated in order
messages:
  - "<#FF4D00>➥ Пᴏлучить гᴀйды и ᴄᴏʙᴇты пᴏ ᴄᴇрʙᴇру мᴏжʜᴏ ʙ /ᴍᴇɴᴜ - Гᴀйды</#FF4D00>"
  - '<#FF4D00>➥ <click:open_url:"https://t.me/vanillasunsteam">У ʜᴀшᴇгᴏ ᴄᴇрʙᴇрᴀ ᴇᴄть ᴄʙᴏй тᴇлᴇгᴘᴀм ᴋᴀʜᴀл ʙ ᴋᴏтᴏᴘᴏм ʙы мᴏжᴇтᴇ узʜᴀʙᴀть ʜᴏʙᴏᴄти пᴇᴘʙыми! Hᴀжмитᴇ ʜᴀ ᴄᴏᴏбщᴇʜиᴇ чтᴏ бы пᴇᴘᴇйти </click></#FF4D00>'
  - '<#FF4D00>➥ <click:open_url:"https://t.me/vanillasunsteam/155">Иʜȹᴏрмᴀция! Hᴀ ᴄᴇрʙᴇрᴇ ᴇᴄть ᴀуᴋциᴏʜ - /ᴀʜ                     Cᴋупщиᴋ - /sᴇʟʟᴇʀ            рᴀбᴏты - /ᴊᴏʙs ʙʀᴏᴡsᴇ</click></#FF4D00>'
  - '<#FF4D00>➥ <click:open_url:"https://t.me/vanillasunsteam/155">Bы мᴏжᴇтᴇ ᴄᴋᴀчᴀть мᴏд ʜᴀ эмоции и гᴏлᴏᴄᴏʙᴏй чᴀт пᴘямᴏ ᴄ ʜᴀшᴇгᴏ тᴇлᴇгᴘᴀм ᴋᴀʜᴀлᴀ чтᴏ бы ᴏбщᴀтьᴄя ᴄ игᴘᴏᴋᴀми! Пᴏдᴘᴏбʜᴇᴇ ʜᴀжᴀʙ ʜᴀ ᴄᴏᴏбщᴇʜиᴇ</click></#FF4D00>'
  - '<#FF4D00>➥ <click:open_url:"https://t.me/vanillasunsteam">Пᴏддᴇᴘжи ᴄᴇрʙᴇр и пᴏлучи пᴘиʙилᴇгии, xᴏᴘᴏший ᴋит! Пᴏдᴘᴏбʜᴇᴇ /ᴅᴏɴᴀᴛᴇ</click></#FF4D00>'

# Broadcast type: CHAT or ACTION_BAR
broadcast-type: CHAT
